--DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(30)		NULL,
	"MEMBER_NICKNAME"	VARCHAR2(60)		NOT NULL,
	"INTRODUCE"	VARCHAR2(2000)		NULL,
	"MEMBER_TEL"	CHAR(13)		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(1000)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	CHAR(1)	DEFAULT 1	NOT NULL,
	"BIRTHYEAR"	CHAR(4)		NULL,
	"BIRTHDAY"	CHAR(4)		NULL,
	"OWN_NO"	NUMBER	DEFAULT 0	NOT NULL,
	"EMOJI_NO"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일(아이디)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '닉네임';

COMMENT ON COLUMN "MEMBER"."INTRODUCE" IS '자기소개';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_YN" IS '탈퇴여부';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '권한';

COMMENT ON COLUMN "MEMBER"."BIRTHYEAR" IS '출생년도';

COMMENT ON COLUMN "MEMBER"."BIRTHDAY" IS '생일';

COMMENT ON COLUMN "MEMBER"."OWN_NO" IS '선택상품번호(폰트)';

COMMENT ON COLUMN "MEMBER"."EMOJI_NO" IS '기분번호';

--DROP TABLE "DIARY";

CREATE TABLE "DIARY" (
	"DIARY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"D_TITLE"	VARCHAR2(100)		NOT NULL,
	"D_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"D_CREATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"D_DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"D_OPEN_FL"	NUMBER	DEFAULT 1	NOT NULL,
	"FOLDER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DIARY"."DIARY_NO" IS '게시글번호';

COMMENT ON COLUMN "DIARY"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "DIARY"."D_TITLE" IS '제목';

COMMENT ON COLUMN "DIARY"."D_CONTENT" IS '내용';

COMMENT ON COLUMN "DIARY"."D_CREATE" IS '작성일';

COMMENT ON COLUMN "DIARY"."D_DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "DIARY"."D_OPEN_FL" IS '글공개여부';

COMMENT ON COLUMN "DIARY"."FOLDER_NO" IS '폴더번호';

--DROP TABLE "EMOJI";

CREATE TABLE "EMOJI" (
	"DIARY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"EMOJI_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "EMOTION"."DIARY_NO" IS '게시글번호';

COMMENT ON COLUMN "EMOTION"."MEMBER_NO" IS '공감 작성자';

COMMENT ON COLUMN "EMOTION"."EMOJI_NO" IS '이모티콘 번호';

--DROP TABLE "ALBUM";

CREATE TABLE "ALBUM" (
	"ALBUM_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"A_TITLE"	VARCHAR2(100)		NOT NULL,
	"A_CONTENT"	VARCHAR2(4000)		NULL,
	"A_CREATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"A_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"LATITUDE"	VARCHAR2(20)		NULL,
	"LONGITUDE"	VARCHAR2(20)		NULL,
	"A_OPEN_FL"	NUMBER	DEFAULT 1	NOT NULL,
	"A_SCRAP_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"FOLDER_NO"	NUMBER		NOT NULL,
	"A_SCRAP_ALLOW_YN"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "ALBUM"."ALBUM_NO" IS '사진첩번호';

COMMENT ON COLUMN "ALBUM"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "ALBUM"."A_TITLE" IS '사진첩제목';

COMMENT ON COLUMN "ALBUM"."A_CONTENT" IS '사진첩내용';

COMMENT ON COLUMN "ALBUM"."A_CREATE" IS '작성일';

COMMENT ON COLUMN "ALBUM"."A_DEL_FL" IS '사진첩 삭제여부';

COMMENT ON COLUMN "ALBUM"."LATITUDE" IS '위도';

COMMENT ON COLUMN "ALBUM"."LONGITUDE" IS '경도';

COMMENT ON COLUMN "ALBUM"."A_OPEN_FL" IS '공개여부';

COMMENT ON COLUMN "ALBUM"."A_SCRAP_YN" IS '스크랩여부';

COMMENT ON COLUMN "ALBUM"."FOLDER_NO" IS '폴더번호';

COMMENT ON COLUMN "ALBUM"."A_SCRAP_ALLOW_YN" IS '스크랩허용여부';

--DROP TABLE "ALBUM_IMG";

CREATE TABLE "ALBUM_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"ALBUM_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(300)		NOT NULL,
	"IMG_RENAME"	VARCHAR2(30)		NOT NULL,
	"IMG_ORDER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ALBUM_IMG"."IMG_NO" IS '이미지 번호';

COMMENT ON COLUMN "ALBUM_IMG"."ALBUM_NO" IS '이미지가 첨부된 사진첩번호';

COMMENT ON COLUMN "ALBUM_IMG"."IMG_PATH" IS '이미지 저장폴더 경로';

COMMENT ON COLUMN "ALBUM_IMG"."IMG_RENAME" IS '변경된 이미지 파일 이름';

COMMENT ON COLUMN "ALBUM_IMG"."IMG_ORDER" IS '이미지 파일 순서 번호';

--DROP TABLE "VIDEO_BOARD";

CREATE TABLE "VIDEO_BOARD" (
	"V_BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"V_TITLE"	VARCHAR2(100)		NOT NULL,
	"V_CONTENT"	VARCHAR2(4000)		NULL,
	"V_CREATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"V_DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"VIDEO_PATH"	VARCHAR2(300)		NOT NULL,
	"VIDEO_RENAME"	VARCHAR2(30)		NOT NULL,
	"V_OPEN_FL"	NUMBER	DEFAULT 1	NOT NULL,
	"V_SCRAP_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"FOLDER_NO"	NUMBER		NULL,
	"V_THUMNAIL"	VARCHAR2(300)		NOT NULL,
	"V_SCRAP_ALLOW_YN"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "VIDEO_BOARD"."V_BOARD_NO" IS '영상글 번호';

COMMENT ON COLUMN "VIDEO_BOARD"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "VIDEO_BOARD"."V_TITLE" IS '영상글제목';

COMMENT ON COLUMN "VIDEO_BOARD"."V_CONTENT" IS '영상글내용';

COMMENT ON COLUMN "VIDEO_BOARD"."V_CREATE" IS '작성일';

COMMENT ON COLUMN "VIDEO_BOARD"."V_DEL_YN" IS '영상글 삭제여부';

COMMENT ON COLUMN "VIDEO_BOARD"."VIDEO_PATH" IS '동영상 저장폴더 경로';

COMMENT ON COLUMN "VIDEO_BOARD"."VIDEO_RENAME" IS '변경된 동영상파일 이름';

COMMENT ON COLUMN "VIDEO_BOARD"."V_OPEN_FL" IS '공개여부';

COMMENT ON COLUMN "VIDEO_BOARD"."V_SCRAP_YN" IS '스크랩여부';

COMMENT ON COLUMN "VIDEO_BOARD"."FOLDER_NO" IS '폴더번호';

COMMENT ON COLUMN "VIDEO_BOARD"."V_THUMNAIL" IS '영상썸네일 경로';

COMMENT ON COLUMN "VIDEO_BOARD"."V_SCRAP_ALLOW_YN" IS '스크랩허용여부';

--DROP TABLE "GUEST_BOOK";

CREATE TABLE "GUEST_BOOK" (
	"GB_NO"	NUMBER		NOT NULL,
	"SENDER_NO"	NUMBER		NOT NULL,
	"RECEIVER_NO"	NUMBER		NOT NULL,
	"GB_CREATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"GB_SECRET_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"GB_CONTENT"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "GUEST_BOOK"."GB_NO" IS '방명록 번호';

COMMENT ON COLUMN "GUEST_BOOK"."SENDER_NO" IS '방명록 보낸회원';

COMMENT ON COLUMN "GUEST_BOOK"."RECEIVER_NO" IS '방명록 받은회원';

COMMENT ON COLUMN "GUEST_BOOK"."GB_CREATE" IS '방명록 작성시간';

COMMENT ON COLUMN "GUEST_BOOK"."GB_SECRET_YN" IS '비밀글 여부';

COMMENT ON COLUMN "GUEST_BOOK"."GB_CONTENT" IS '방명록내용';

--DROP TABLE "GOODS_SHOP";

CREATE TABLE "GOODS_SHOP" (
	"GOODS_NO"	NUMBER		NOT NULL,
	"GOODS_NAME"	VARCHAR2(100)		NOT NULL,
	"GOODS_PATH"	VARCHAR2(100)		NOT NULL,
	"GOODS_CREATER"	VARCHAR2(100)	DEFAULT 'CUBESPACE'	NOT NULL
);

COMMENT ON COLUMN "GOODS_SHOP"."GOODS_NO" IS '소품 번호';

COMMENT ON COLUMN "GOODS_SHOP"."GOODS_NAME" IS '소품이름';

COMMENT ON COLUMN "GOODS_SHOP"."GOODS_PATH" IS '소품 URL';

COMMENT ON COLUMN "GOODS_SHOP"."GOODS_CREATER" IS '소품 제작자';

--DROP TABLE "EMOJI_IMG";

CREATE TABLE "EMOJI_IMG" (
	"EMOJI_NO"	NUMBER		NOT NULL,
	"EMOJI_PATH"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "EMOJI_IMG"."EMOJI_NO" IS '이모티콘 번호';

COMMENT ON COLUMN "EMOJI_IMG"."EMOJI_PATH" IS '이모티콘 이미지 경로';

--DROP TABLE "SHOP_CATEGORY";

CREATE TABLE "SHOP_CATEGORY" (
	"SHOP_CATH_NO"	NUMBER		NOT NULL,
	"SHOP_CATH_NAME"	VARCHAR2(21)		NOT NULL
);

COMMENT ON COLUMN "SHOP_CATEGORY"."SHOP_CATH_NO" IS '상점 카테고리번호';

COMMENT ON COLUMN "SHOP_CATEGORY"."SHOP_CATH_NAME" IS '상점 카테고리 이름';

--DROP TABLE "MUSIC_SHOP";

CREATE TABLE "MUSIC_SHOP" (
	"MUSIC_NO"	NUMBER		NOT NULL,
	"MUSIC_NAME"	VARCHAR2(300)		NOT NULL,
	"MUSIC_PATH"	VARCHAR2(100)		NOT NULL,
	"MUSIC_THUMNAIL"	VARCHAR2(100)		NOT NULL,
	"MUSIC_CREATER"	VARCHAR2(100)	DEFAULT 'UNKNOWN'	NOT NULL
);

COMMENT ON COLUMN "MUSIC_SHOP"."MUSIC_NO" IS '배경음악 번호';

COMMENT ON COLUMN "MUSIC_SHOP"."MUSIC_NAME" IS '배경음악 이름';

COMMENT ON COLUMN "MUSIC_SHOP"."MUSIC_PATH" IS '배경음악 경로';

COMMENT ON COLUMN "MUSIC_SHOP"."MUSIC_THUMNAIL" IS '배경음악썸네일 경로';

COMMENT ON COLUMN "MUSIC_SHOP"."MUSIC_CREATER" IS '배경음악 제작자';



--DROP TABLE "FRIEND";

CREATE TABLE "FRIEND" (
	"ASKED_MEMBER_NO"	NUMBER		NOT NULL,
	"ASKING_MEMBER_NO"	NUMBER		NOT NULL,
	"FRIEND_ACCEPT_FL"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "FRIEND"."ASKED_MEMBER_NO" IS '요청받은 회원번호';

COMMENT ON COLUMN "FRIEND"."ASKING_MEMBER_NO" IS '요청한 회원번호';

COMMENT ON COLUMN "FRIEND"."FRIEND_ACCEPT_FL" IS '깐부 수락여부';




--DROP TABLE "MEMBER_COMPLAIN";

CREATE TABLE "MEMBER_COMPLAIN" (
	"COMPLAIN_NO"	NUMBER		NOT NULL,
	"COMPLAINER_NO"	NUMBER		NOT NULL,
	"COMPLAINED_NO"	NUMBER		NOT NULL,
	"COMPLAIN_CONTENT"	VARCHAR2(900)		NOT NULL,
	"C_CREATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "MEMBER_COMPLAIN"."COMPLAIN_NO" IS '회원신고번호';

COMMENT ON COLUMN "MEMBER_COMPLAIN"."COMPLAINER_NO" IS '신고한 사람';

COMMENT ON COLUMN "MEMBER_COMPLAIN"."COMPLAINED_NO" IS '신고당한 사람';

COMMENT ON COLUMN "MEMBER_COMPLAIN"."COMPLAIN_CONTENT" IS '신고내용';

COMMENT ON COLUMN "MEMBER_COMPLAIN"."C_CREATE" IS '작성일';

--DROP TABLE "MEMBER_BLOCK";

CREATE TABLE "MEMBER_BLOCK" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BLOCK_START"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BLOCK_END"	DATE		NOT NULL
);

COMMENT ON COLUMN "MEMBER_BLOCK"."MEMBER_NO" IS '정지회원번호';

COMMENT ON COLUMN "MEMBER_BLOCK"."BLOCK_START" IS '정지시작시간';

COMMENT ON COLUMN "MEMBER_BLOCK"."BLOCK_END" IS '정지끝시간';

--DROP TABLE "MEMBER_OWN_GOODS";

CREATE TABLE "MEMBER_OWN_GOODS" (
	"OWN_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"SHOP_CATH_NO"	NUMBER		NOT NULL,
	"GOODS_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER_OWN_GOODS"."OWN_NO" IS '소유상품번호';

COMMENT ON COLUMN "MEMBER_OWN_GOODS"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER_OWN_GOODS"."SHOP_CATH_NO" IS '상점 카테고리번호';

COMMENT ON COLUMN "MEMBER_OWN_GOODS"."GOODS_NO" IS '상품번호';

--DROP TABLE "FONT_SHOP";

CREATE TABLE "FONT_SHOP" (
	"FONT_NO"	NUMBER		NOT NULL,
	"FONT_NAME"	VARCHAR2(100)		NOT NULL,
	"FONT_PATH"	VARCHAR2(100)		NOT NULL,
	"FONT_CREATER"	VARCHAR2(100)	DEFAULT 'UNKNOWN'	NOT NULL
);

COMMENT ON COLUMN "FONT_SHOP"."FONT_NO" IS '폰트 번호';

COMMENT ON COLUMN "FONT_SHOP"."FONT_NAME" IS '폰트 이름';

COMMENT ON COLUMN "FONT_SHOP"."FONT_PATH" IS '폰트 경로';

COMMENT ON COLUMN "FONT_SHOP"."FONT_CREATER" IS '폰트 제작자';

--DROP TABLE "MINI_HOMEPAGE";

CREATE TABLE "MINI_HOMEPAGE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"HOMEPAGE_NAME"	VARCHAR2(30)	DEFAULT 마이 홈페이지	NOT NULL,
	"BACKGROUND_SKIN"	VARCHAR2(255)	DEFAULT 'rgb(128,128,128)'	NOT NULL,
	"COMMENT"	VARCHAR2(3000)		NULL,
	"COUNT_TODAY"	NUMBER	DEFAULT 0	NOT NULL,
	"COUNT_ALL"	NUMBER	DEFAULT 0	NOT NULL,
	"OWN_NO"	NUMBER		NOT NULL,
	"FRAME_COLOR"	VARCHAR2(50)		NOT NULL,
	"FRAME_MENU_COLOR"	VARCHAR2(50)		NOT NULL,
	"FRAME_FONT_COLOR"	VARCHAR2(50)	DEFAULT 'WHITE'	NOT NULL
);

COMMENT ON COLUMN "MINI_HOMEPAGE"."MEMBER_NO" IS '미니홈피 호스트회원 번호';

COMMENT ON COLUMN "MINI_HOMEPAGE"."HOMEPAGE_NAME" IS '미니홈피이름';

COMMENT ON COLUMN "MINI_HOMEPAGE"."BACKGROUND_SKIN" IS '배경 스킨';

COMMENT ON COLUMN "MINI_HOMEPAGE"."COMMENT" IS '홈페이지 소개글';

COMMENT ON COLUMN "MINI_HOMEPAGE"."COUNT_TODAY" IS '일일방문자수';

COMMENT ON COLUMN "MINI_HOMEPAGE"."COUNT_ALL" IS '총방문자수';

COMMENT ON COLUMN "MINI_HOMEPAGE"."OWN_NO" IS '소유상품번호(음악)';

COMMENT ON COLUMN "MINI_HOMEPAGE"."FRAME_COLOR" IS '프레임색';

COMMENT ON COLUMN "MINI_HOMEPAGE"."FRAME_MENU_COLOR" IS '프레임메뉴색';

COMMENT ON COLUMN "MINI_HOMEPAGE"."FRAME_FONT_COLOR" IS '프레임글자색';

--DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"COMMENT_CONENT"	VARCHAR2(300)		NOT NULL,
	"COMMENT_CREATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PARENT_COMMENT_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글번호';

COMMENT ON COLUMN "COMMENT"."BOARD_TYPE_NO" IS '게시판타입번호';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONENT" IS '댓글내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_CREATE" IS '댓글작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "COMMENT"."PARENT_COMMENT_NO" IS '부모댓글번호';

--DROP TABLE "BOARD_TYPE";

CREATE TABLE "BOARD_TYPE" (
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NAME"	VARCHAR2(21)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_NO" IS '게시판 타입번호';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_NAME" IS '게시판 카테고리 이름';

--DROP TABLE "FOLDER";

CREATE TABLE "FOLDER" (
	"FOLDER_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"FOLDER_NAME"	VARCHAR2(300)		NOT NULL,
	"FOLDER_ORDER"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "FOLDER"."FOLDER_NO" IS '폴더번호';

COMMENT ON COLUMN "FOLDER"."BOARD_TYPE_NO" IS '게시판 타입번호';

COMMENT ON COLUMN "FOLDER"."FOLDER_NAME" IS '폴더이름';

COMMENT ON COLUMN "FOLDER"."FOLDER_ORDER" IS '폴더순서';

COMMENT ON COLUMN "FOLDER"."MEMBER_NO" IS '회원번호';

--DROP TABLE "CATEGORY_ORDER";

CREATE TABLE "CATEGORY_ORDER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"DIARY"	NUMBER	DEFAULT 1	NOT NULL,
	"ALBUM"	NUMBER	DEFAULT 2	NOT NULL,
	"VIDEO"	NUMBER	DEFAULT 3	NOT NULL,
	"GUEST_BOOK"	NUMBER	DEFAULT 4	NOT NULL
);

COMMENT ON COLUMN "CATEGORY_ORDER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "CATEGORY_ORDER"."DIARY" IS '다이어리';

COMMENT ON COLUMN "CATEGORY_ORDER"."ALBUM" IS '사진첩';

COMMENT ON COLUMN "CATEGORY_ORDER"."VIDEO" IS '동영상';

COMMENT ON COLUMN "CATEGORY_ORDER"."GUEST_BOOK" IS '방명록';

--DROP TABLE "PLAN";

CREATE TABLE "PLAN" (
	"PLAN_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NOT NULL,
	"PLAN_TITLE"	VARCHAR2(300)		NOT NULL
);

COMMENT ON COLUMN "PLAN"."PLAN_NO" IS '일정번호';

COMMENT ON COLUMN "PLAN"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "PLAN"."START_DATE" IS '시작날짜';

COMMENT ON COLUMN "PLAN"."END_DATE" IS '끝날짜';

COMMENT ON COLUMN "PLAN"."PLAN_TITLE" IS '일정제목';

--DROP TABLE "EMOJI";

CREATE TABLE "EMOTION" (
	"EMOTION_NO"	NUMBER		NOT NULL,
	"EMOTION_PATH"	VARCHAR2(100)		NOT NULL,
	"EMOTION_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "EMOTION"."EMOTION_NO" IS '기분번호';

COMMENT ON COLUMN "EMOTION"."EMOTION_PATH" IS '기분 경로';

COMMENT ON COLUMN "EMOTION"."EMOTION_NAME" IS '기분 이름';

--DROP TABLE "FRIEND_COMMENT";

CREATE TABLE "FRIEND_COMMENT" (
	"F_COMMENT_NO"	NUMBER		NOT NULL,
	"F_CONENT"	VARCHAR2(300)		NOT NULL,
	"F_CREATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"F_WRITER_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "FRIEND_COMMENT"."F_COMMENT_NO" IS '댓글번호';

COMMENT ON COLUMN "FRIEND_COMMENT"."F_CONENT" IS '댓글내용';

COMMENT ON COLUMN "FRIEND_COMMENT"."F_CREATE" IS '댓글작성일';

COMMENT ON COLUMN "FRIEND_COMMENT"."F_WRITER_NO" IS '회원번호';

COMMENT ON COLUMN "FRIEND_COMMENT"."MEMBER_NO" IS '미니홈피 주인번호';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "DIARY" ADD CONSTRAINT "PK_DIARY" PRIMARY KEY (
	"DIARY_NO"
);

ALTER TABLE "EMOJI" ADD CONSTRAINT "PK_EMOJI" PRIMARY KEY (
	"DIARY_NO"
);

ALTER TABLE "ALBUM" ADD CONSTRAINT "PK_ALBUM" PRIMARY KEY (
	"ALBUM_NO"
);

ALTER TABLE "ALBUM_IMG" ADD CONSTRAINT "PK_ALBUM_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "VIDEO_BOARD" ADD CONSTRAINT "PK_VIDEO_BOARD" PRIMARY KEY (
	"V_BOARD_NO"
);

ALTER TABLE "GUEST_BOOK" ADD CONSTRAINT "PK_GUEST_BOOK" PRIMARY KEY (
	"GB_NO"
);

ALTER TABLE "GOODS_SHOP" ADD CONSTRAINT "PK_GOODS_SHOP" PRIMARY KEY (
	"GOODS_NO"
);

ALTER TABLE "EMOJI_IMG" ADD CONSTRAINT "PK_EMOJI_IMG" PRIMARY KEY (
	"EMOJI_NO"
);

ALTER TABLE "SHOP_CATEGORY" ADD CONSTRAINT "PK_SHOP_CATEGORY" PRIMARY KEY (
	"SHOP_CATH_NO"
);

ALTER TABLE "MUSIC_SHOP" ADD CONSTRAINT "PK_MUSIC_SHOP" PRIMARY KEY (
	"MUSIC_NO"
);



ALTER TABLE "FRIEND" ADD CONSTRAINT "PK_FRIEND" PRIMARY KEY (
	"ASKED_MEMBER_NO",
	"ASKING_MEMBER_NO"
);



ALTER TABLE "MEMBER_COMPLAIN" ADD CONSTRAINT "PK_MEMBER_COMPLAIN" PRIMARY KEY (
	"COMPLAIN_NO"
);

ALTER TABLE "MEMBER_BLOCK" ADD CONSTRAINT "PK_MEMBER_BLOCK" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_OWN_GOODS" ADD CONSTRAINT "PK_MEMBER_OWN_GOODS" PRIMARY KEY (
	"OWN_NO"
);

ALTER TABLE "FONT_SHOP" ADD CONSTRAINT "PK_FONT_SHOP" PRIMARY KEY (
	"FONT_NO"
);

ALTER TABLE "MINI_HOMEPAGE" ADD CONSTRAINT "PK_MINI_HOMEPAGE" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_TYPE_NO"
);

ALTER TABLE "FOLDER" ADD CONSTRAINT "PK_FOLDER" PRIMARY KEY (
	"FOLDER_NO"
);

ALTER TABLE "CATEGORY_ORDER" ADD CONSTRAINT "PK_CATEGORY_ORDER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "PLAN" ADD CONSTRAINT "PK_PLAN" PRIMARY KEY (
	"PLAN_NO"
);

ALTER TABLE "EMOJI" ADD CONSTRAINT "PK_EMOJI" PRIMARY KEY (
	"EMOJI_NO"
);

ALTER TABLE "FRIEND_COMMENT" ADD CONSTRAINT "PK_FRIEND_COMMENT" PRIMARY KEY (
	"F_COMMENT_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_MEMBER_OWN_GOODS_TO_MEMBER_1" FOREIGN KEY (
	"OWN_NO"
)
REFERENCES "MEMBER_OWN_GOODS" (
	"OWN_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_EMOJI_TO_MEMBER_1" FOREIGN KEY (
	"EMOJI_NO"
)
REFERENCES "EMOJI" (
	"EMOJI_NO"
);

ALTER TABLE "DIARY" ADD CONSTRAINT "FK_MEMBER_TO_DIARY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "DIARY" ADD CONSTRAINT "FK_FOLDER_TO_DIARY_1" FOREIGN KEY (
	"FOLDER_NO"
)
REFERENCES "FOLDER" (
	"FOLDER_NO"
);

ALTER TABLE "EMOJI" ADD CONSTRAINT "FK_DIARY_TO_EMOJI_1" FOREIGN KEY (
	"DIARY_NO"
)
REFERENCES "DIARY" (
	"DIARY_NO"
);

ALTER TABLE "EMOJI" ADD CONSTRAINT "FK_MEMBER_TO_EMOJI_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "EMOJI" ADD CONSTRAINT "FK_EMOJI_IMG_TO_EMOJI_1" FOREIGN KEY (
	"EMOJI_NO"
)
REFERENCES "EMOJI_IMG" (
	"EMOJI_NO"
);

ALTER TABLE "ALBUM" ADD CONSTRAINT "FK_MEMBER_TO_ALBUM_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "ALBUM" ADD CONSTRAINT "FK_FOLDER_TO_ALBUM_1" FOREIGN KEY (
	"FOLDER_NO"
)
REFERENCES "FOLDER" (
	"FOLDER_NO"
);

ALTER TABLE "ALBUM_IMG" ADD CONSTRAINT "FK_ALBUM_TO_ALBUM_IMG_1" FOREIGN KEY (
	"ALBUM_NO"
)
REFERENCES "ALBUM" (
	"ALBUM_NO"
);

ALTER TABLE "VIDEO_BOARD" ADD CONSTRAINT "FK_MEMBER_TO_VIDEO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "GUEST_BOOK" ADD CONSTRAINT "FK_MEMBER_TO_GUEST_BOOK_1" FOREIGN KEY (
	"SENDER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "GUEST_BOOK" ADD CONSTRAINT "FK_MEMBER_TO_GUEST_BOOK_2" FOREIGN KEY (
	"RECEIVER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "FRIEND" ADD CONSTRAINT "FK_MEMBER_TO_FRIEND_1" FOREIGN KEY (
	"ASKING_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);



ALTER TABLE "MEMBER_COMPLAIN" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_COMPLAIN_1" FOREIGN KEY (
	"COMPLAINER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_COMPLAIN" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_COMPLAIN_2" FOREIGN KEY (
	"COMPLAINED_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_BLOCK" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_BLOCK_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_OWN_GOODS" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_OWN_GOODS_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_OWN_GOODS" ADD CONSTRAINT "FK_SHOP_CATEGORY_TO_MEMBER_OWN_GOODS_1" FOREIGN KEY (
	"SHOP_CATH_NO"
)
REFERENCES "SHOP_CATEGORY" (
	"SHOP_CATH_NO"
);

ALTER TABLE "MINI_HOMEPAGE" ADD CONSTRAINT "FK_MEMBER_TO_MINI_HOMEPAGE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MINI_HOMEPAGE" ADD CONSTRAINT "FK_MEMBER_OWN_GOODS_TO_MINI_HOMEPAGE_1" FOREIGN KEY (
	"OWN_NO"
)
REFERENCES "MEMBER_OWN_GOODS" (
	"OWN_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"PARENT_COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "FOLDER" ADD CONSTRAINT "FK_BOARD_TYPE_TO_FOLDER_1" FOREIGN KEY (
	"BOARD_TYPE_NO"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_NO"
);

ALTER TABLE "FOLDER" ADD CONSTRAINT "FK_MEMBER_TO_FOLDER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CATEGORY_ORDER" ADD CONSTRAINT "FK_MEMBER_TO_CATEGORY_ORDER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "PLAN" ADD CONSTRAINT "FK_MEMBER_TO_PLAN_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "FRIEND_COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_FRIEND_COMMENT_1" FOREIGN KEY (
	"F_WRITER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "FRIEND_COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_FRIEND_COMMENT_2" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

COMMIT;

ALTER TABLE FRIEND DROP COLUMN ILCHON_ACCEPT_FL;


UPDATE FOLDER SET
FOLDER_ORDER = 2
WHERE FOLDER_NAME = '나의 다이어리';

SELECT * FROM FOLDER;


CREATE TABLE "ALARM" (
	"ALARM_NO"	NUMBER		NOT NULL,
	"SENDER_NO"	NUMBER		NOT NULL,
	"RECEIVER_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"ALARM_TYPE"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"ALARM_CREATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "ALARM"."ALARM_NO" IS '알람번호';

COMMENT ON COLUMN "ALARM"."SENDER_NO" IS '보내는사람';

COMMENT ON COLUMN "ALARM"."RECEIVER_NO" IS '받는사람';

COMMENT ON COLUMN "ALARM"."BOARD_TYPE_NO" IS '게시판 타입번호';

COMMENT ON COLUMN "ALARM"."ALARM_TYPE" IS '알람타입';

COMMENT ON COLUMN "ALARM"."BOARD_NO" IS '글번호';

COMMENT ON COLUMN "ALARM"."ALARM_CREATE" IS '알람생성시간';

ALTER TABLE "ALARM" ADD CONSTRAINT "PK_ALARM" PRIMARY KEY (
	"ALARM_NO"
);

SELECT * FROM ALBUM;
COMMIT;

SELECT * FROM FRIEND;

ALTER TABLE FRIEND ADD CONSTRAINT PFK_MEMBER_NO PRIMARY KEY(ASKED_MEMBER_NO, ASKING_MEMBER_NO);


CREATE SEQUENCE SEQ_MEMBER_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_EMOTION_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_OWN_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_GOODS_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_MUSIC_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_FONT_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_F_COMMENT_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_DIARY_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_ALBUM_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_IMG_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_V_BOARD_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_GB_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_COMPLAIN_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_PLAN_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_FOLDER_NO
	NOCYCLE
	NOCACHE;
CREATE SEQUENCE SEQ_ALARM_NO
	NOCYCLE
	NOCACHE;
	
SELECT SEQ_FOLDER_NO.NEXTVAL FROM DUAL;

COMMIT;

